#!/bin/sh

# Copyright (c) 2010       Masahiro Ide <imasahiro9@gmail.com>
# shinpei@ynu(c)2008

test -f AUTHORS   || touch AUTHORS
test -f COPYING   || touch COPYING
test -f ChangeLog || touch ChangeLog
test -f NEWS      || touch NEWS
test -f README    || touch README

test -e config || mkdir config

ACLOCAL="aclocal"
AUTOCONF="autoconf"
AUTOHEADER="autoheader"
AUTOMAKE="automake"
if [ x`uname` = x"Darwin" ]; then
	LIBTOOLIZE="glibtoolize --force --copy"
else
	LIBTOOLIZE="libtoolize --force --copy"
fi

$ACLOCAL -I config
$LIBTOOLIZE 
$AUTOHEADER
$AUTOMAKE -af
$AUTOCONF

