.TH KONOHA 1 "2010-08-20" "Konoha Software Foundation" "Scripting Language"
.SH NAME
.B konoha
\- a statically-typed object-oriented scripting language
.SH SYNOPSIS
.B konoha
[
.I options
] 
[
.I file
]
.SH DESCRIPTION
.B Konoha
is a statically typed object-oriented scripting language, that provides the 
best integration of scripting into software development.
.PP
The default install package directory is $HOME/.konoha/package .

.SH COMMAND LINE OPTIONS
\fB-v\fP
verbose mode.
.TP
\fB-c\fP
compiler only.
.TP
\fB-i\fP
When a script is passed as first argument, 
enter the interactive mode after executing the script.
.SH ENVIRONMENT VARIABLES
.TP
.B KONOHA_HOME
switch installed konoha directory
.TP
.B KONOHA_PACKAGE
additional path for laoding packages
.SH SEE ALSO
.TP
\fBklip\fP
Installer for konoha package Library
.SH MORE INFORMATION
http://code.google.com/p/konoha (International)
.br
http://konoha.sourceforge.jp/  (in Japanese)
.SH AUTHOR
Kimio Kuramitsu <kimio at ynu.ac.jp>
.br
Konoha Team <konohaken@googlegroups.com> (You are welcome)
