float f1(float x, float y){
	return x + y;
}
float f2(float x, float y){
	return x - y;
}
float f3(float x, float y){
	return x * y;
}
float f4(float x, float y){
	return x / y;
}
float f5(float x){
	return x + 10;
}
float f6(float x){
	return x - 10;
}
float f7(float x){
	return x * 10;
}
float f8(float x){
	return x / 10;
}
boolean f9(float x, float y){
	return x <= y;
}
boolean f10(float x, float y){
	return x < y;
}
boolean f11(float x, float y){
	return x > y;
}
boolean f12(float x, float y){
	return x >= y;
}
float f13(float x){
	return -x;
}
