float f0(float a, float b) {
	return a + b;
}
float f1(float a, float b) {
	return a - b;
}
float f2(float a, float b) {
	return a * b;
}
float f3(float a, float b) {
	return a / b;
}
boolean f4(float a, float b) {
	return a == b;
}
boolean f5(float a, float b) {
	return a != b;
}
boolean f6(float a, float b) {
	return a < b;
}
boolean f7(float a, float b) {
	return a <= b;
}
boolean f8(float a, float b) {
	return a > b;
}
boolean f9(float a, float b) {
	return a >= b;
}
float f10(float a) {
	return -a;
}
