int f0(int a, int b) {
	return a + b;
}
int f1(int a, int b) {
	return a - b;
}
int f2(int a, int b) {
	return a * b;
}
int f3(int a, int b) {
	return a / b;
}
int f4(int a, int b) {
	return a % b;
}
boolean f5(int a, int b) {
	return a == b;
}
boolean f6(int a, int b) {
	return a != b;
}
boolean f7(int a, int b) {
	return a < b;
}
boolean f8(int a, int b) {
	return a <= b;
}
boolean f9(int a, int b) {
	return a > b;
}
boolean f10(int a, int b) {
	return a >= b;
}
int f11(int a, int b) {
	return a & b;
}
int f12(int a, int b) {
	return a | b;
}
int f13(int a, int b) {
	return a ^ b;
}
int f14(int a, int b) {
	return a << b;
}
int f15(int a, int b) {
	return a >> b;
}
int f16(int a) {
	return -a;
}
