// THIS FILE WAS AUTOMATICALLY GENERATED

/* ======================================================================== */
/* flag */

static METHOD String_isASCII(Ctx *ctx, knh_sfp_t *sfp, long rix)
{
	RETURNb_(knh_String_isASCII((knh_String_t*)sfp[0].o));
}

static METHOD OutputStream_isAutoFlush(Ctx *ctx, knh_sfp_t *sfp, long rix)
{
	RETURNb_(knh_OutputStream_isAutoFlush((knh_OutputStream_t*)sfp[0].o));
}

static METHOD OutputStream_setAutoFlush(Ctx *ctx, knh_sfp_t *sfp, long rix)
{
	knh_OutputStream_setAutoFlush((knh_OutputStream_t*)sfp[0].o, sfp[1].bvalue);
	RETURNb_(sfp[1].bvalue);
}

static METHOD Context_isDebug(Ctx *ctx, knh_sfp_t *sfp, long rix)
{
	RETURNb_(knh_Context_isDebug((knh_Context_t*)sfp[0].o));
}

static METHOD Context_setDebug(Ctx *ctx, knh_sfp_t *sfp, long rix)
{
	knh_Context_setDebug((knh_Context_t*)sfp[0].o, sfp[1].bvalue);
	RETURNb_(sfp[1].bvalue);
}

static METHOD Context_isVerbose(Ctx *ctx, knh_sfp_t *sfp, long rix)
{
	RETURNb_(knh_Context_isVerbose((knh_Context_t*)sfp[0].o));
}

static METHOD Context_setVerbose(Ctx *ctx, knh_sfp_t *sfp, long rix)
{
	knh_Context_setVerbose((knh_Context_t*)sfp[0].o, sfp[1].bvalue);
	RETURNb_(sfp[1].bvalue);
}

/* ======================================================================== */
/* data */

static const char * StringData0[] = {
	"", /* TS_EMPTY */
	"\t", /* TS_TAB */
	"1", /* TS_ONE */
	""KONOHA_OS_LINEFEED"", /* TS_EOL */
	"BEGIN", /* TS_BEGIN */
	"END", /* TS_END */
	"true", /* TS_true */
	"false", /* TS_false */
	"null", /* TS_null */
	"void", /* TS_void */
	"main", /* TS_main */
	""K_ENCODING"", /* TS_ENCODING */
	"/dev/null", /* TS_DEVNULL */
	"/dev/stdin", /* TS_DEVSTDIN */
	"/dev/stderr", /* TS_DEVSTDERR */
	"/dev/stdout", /* TS_DEVSTDOUT */
	"@label", /* TS_ATlabel */
	"Assertion!!", /* TS_AssertionException */
	"(", /* TS_LP */
	")", /* TS_RP */
	"{", /* TS_LB */
	"}", /* TS_RB */
	"[", /* TS_LS */
	"]", /* TS_RS */
	NULL
};

static knh_data_t StructData0[] = {
	DATA_STRUCT, CLASS_Object, _DATA(&ObjectSPI), FLAG_Object,
	DATA_STRUCT, CLASS_Boolean, _DATA(&BooleanSPI), FLAG_Boolean,
	DATA_STRUCT, CLASS_Number, _DATA(&NumberSPI), FLAG_Number,
	DATA_STRUCT, CLASS_Int, _DATA(&IntSPI), FLAG_Int,
	DATA_STRUCT, CLASS_Float, _DATA(&FloatSPI), FLAG_Float,
	DATA_STRUCT, CLASS_String, _DATA(&StringSPI), FLAG_String,
	DATA_STRUCT, CLASS_Bytes, _DATA(&BytesSPI), FLAG_Bytes,
	DATA_STRUCT, CLASS_Any, _DATA(&AnySPI), FLAG_Any,
	DATA_STRUCT, CLASS_Iterator, _DATA(&IteratorSPI), FLAG_Iterator,
	DATA_STRUCT, CLASS_Tuple, _DATA(&TupleSPI), FLAG_Tuple,
	DATA_STRUCT, CLASS_Range, _DATA(&RangeSPI), FLAG_Range,
	DATA_STRUCT, CLASS_Array, _DATA(&ArraySPI), FLAG_Array,
	DATA_STRUCT, CLASS_Map, _DATA(&MapSPI), FLAG_Map,
	DATA_STRUCT, CLASS_Class, _DATA(&ClassSPI), FLAG_Class,
	DATA_STRUCT, CLASS_ParamArray, _DATA(&ParamArraySPI), FLAG_ParamArray,
	DATA_STRUCT, CLASS_Method, _DATA(&MethodSPI), FLAG_Method,
	DATA_STRUCT, CLASS_Translator, _DATA(&TranslatorSPI), FLAG_Translator,
	DATA_STRUCT, CLASS_Func, _DATA(&FuncSPI), FLAG_Func,
	DATA_STRUCT, CLASS_Thunk, _DATA(&ThunkSPI), FLAG_Thunk,
	DATA_STRUCT, CLASS_Exception, _DATA(&ExceptionSPI), FLAG_Exception,
	DATA_STRUCT, CLASS_ExceptionHandler, _DATA(&ExceptionHandlerSPI), FLAG_ExceptionHandler,
	DATA_STRUCT, CLASS_Regex, _DATA(&RegexSPI), FLAG_Regex,
	DATA_STRUCT, CLASS_Converter, _DATA(&ConverterSPI), FLAG_Converter,
	DATA_STRUCT, CLASS_StringEncoder, _DATA(&StringEncoderSPI), FLAG_StringEncoder,
	DATA_STRUCT, CLASS_StringDecoder, _DATA(&StringDecoderSPI), FLAG_StringDecoder,
	DATA_STRUCT, CLASS_StringConverter, _DATA(&StringConverterSPI), FLAG_StringConverter,
	DATA_STRUCT, CLASS_Semantics, _DATA(&SemanticsSPI), FLAG_Semantics,
	DATA_STRUCT, CLASS_InputStream, _DATA(&InputStreamSPI), FLAG_InputStream,
	DATA_STRUCT, CLASS_OutputStream, _DATA(&OutputStreamSPI), FLAG_OutputStream,
	DATA_STRUCT, CLASS_Connection, _DATA(&ConnectionSPI), FLAG_Connection,
	DATA_STRUCT, CLASS_ResultSet, _DATA(&ResultSetSPI), FLAG_ResultSet,
	DATA_STRUCT, CLASS_Script, _DATA(&ScriptSPI), FLAG_Script,
	DATA_STRUCT, CLASS_NameSpace, _DATA(&NameSpaceSPI), FLAG_NameSpace,
	DATA_STRUCT, CLASS_Package, _DATA(&PackageSPI), FLAG_Package,
	DATA_STRUCT, CLASS_System, _DATA(&SystemSPI), FLAG_System,
	DATA_STRUCT, CLASS_Context, _DATA(&ContextSPI), FLAG_Context,
	DATA_STRUCT, CLASS_Term, _DATA(&TermSPI), FLAG_Term,
	DATA_STRUCT, CLASS_Token, _DATA(&TokenSPI), FLAG_Token,
	DATA_STRUCT, CLASS_Stmt, _DATA(&StmtSPI), FLAG_Stmt,
	DATA_STRUCT, CLASS_Gamma, _DATA(&GammaSPI), FLAG_Gamma,
	DATA_STRUCT, CLASS_BasicBlock, _DATA(&BasicBlockSPI), FLAG_BasicBlock,
	DATA_STRUCT, CLASS_KLRCode, _DATA(&KLRCodeSPI), FLAG_KLRCode,
	0
};

static knh_data_t ClassData0[] = {
	DATA_CLASS, _DATA("konoha.Object"), FLAG_Object, CLASS_ObjectField, CLASS_Object, 17 + 5 /*1*/,
	DATA_CLASS, _DATA("konoha.Boolean"), FLAG_Boolean, CLASS_Boolean, CLASS_Object, 1 + 1 /*0*/,
	DATA_CLASS, _DATA("konoha.Number"), FLAG_Number, CLASS_Number, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Int"), FLAG_Int, CLASS_Int, CLASS_Number, 20 + 8 /*1*/,
	DATA_CLASS, _DATA("konoha.Float"), FLAG_Float, CLASS_Float, CLASS_Number, 13 + 5 /*1*/,
	DATA_CLASS, _DATA("konoha.String"), FLAG_String, CLASS_String, CLASS_Object, 26 + 2 /*4*/,
	DATA_CLASS, _DATA("konoha.Bytes"), FLAG_Bytes, CLASS_Bytes, CLASS_Object, 13 + 2 /*1*/,
	DATA_CLASS, _DATA("konoha.Any"), FLAG_Any, CLASS_Any, CLASS_Object, 6 + 1 /*0*/,
	DATA_CLASS, _DATA("konoha.Iterator"), FLAG_Iterator, CLASS_Iterator, CLASS_Object, 0 + 1 /*1*/,
	DATA_CLASS, _DATA("konoha.Tuple"), FLAG_Tuple, CLASS_Tuple, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Range"), FLAG_Range, CLASS_Range, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Array"), FLAG_Array, CLASS_Array, CLASS_Object, 13 + 1 /*1*/,
	DATA_CLASS, _DATA("konoha.Map"), FLAG_Map, CLASS_Map, CLASS_Object, 8 + 1 /*2*/,
	DATA_CLASS, _DATA("konoha.Class"), FLAG_Class, CLASS_Class, CLASS_Object, 1 + 3 /*0*/,
	DATA_CLASS, _DATA("konoha.ParamArray"), FLAG_ParamArray, CLASS_ParamArray, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Method"), FLAG_Method, CLASS_Method, CLASS_Object, 2 + 3 /*0*/,
	DATA_CLASS, _DATA("konoha.Translator"), FLAG_Translator, CLASS_Translator, CLASS_Object, 0 + 1 /*0*/,
	DATA_CLASS, _DATA("konoha.Func"), FLAG_Func, CLASS_Func, CLASS_Object, 3 + 1 /*0*/,
	DATA_CLASS, _DATA("konoha.Thunk"), FLAG_Thunk, CLASS_Thunk, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Exception"), FLAG_Exception, CLASS_Exception, CLASS_Object, 2 + 2 /*0*/,
	DATA_CLASS, _DATA("konoha.ExceptionHandler"), FLAG_ExceptionHandler, CLASS_ExceptionHandler, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Regex"), FLAG_Regex, CLASS_Regex, CLASS_Object, 2 + 1 /*0*/,
	DATA_CLASS, _DATA("konoha.Converter"), FLAG_Converter, CLASS_Converter, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.StringEncoder"), FLAG_StringEncoder, CLASS_StringEncoder, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.StringDecoder"), FLAG_StringDecoder, CLASS_StringDecoder, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.StringConverter"), FLAG_StringConverter, CLASS_StringConverter, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Semantics"), FLAG_Semantics, CLASS_Semantics, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.InputStream"), FLAG_InputStream, CLASS_InputStream, CLASS_Object, 7 + 1 /*1*/,
	DATA_CLASS, _DATA("konoha.OutputStream"), FLAG_OutputStream, CLASS_OutputStream, CLASS_Object, 14 + 1 /*0*/,
	DATA_CLASS, _DATA("konoha.Connection"), FLAG_Connection, CLASS_Connection, CLASS_Object, 4 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.ResultSet"), FLAG_ResultSet, CLASS_ResultSet, CLASS_Object, 8 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Script"), FLAG_Script, CLASS_Script, CLASS_Object, 0 + 1 /*0*/,
	DATA_CLASS, _DATA("konoha.NameSpace"), FLAG_NameSpace, CLASS_NameSpace, CLASS_Object, 1 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Package"), FLAG_Package, CLASS_Package, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.System"), FLAG_System, CLASS_System, CLASS_Object, 9 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Context"), FLAG_Context, CLASS_Context, CLASS_Object, 7 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Term"), FLAG_Term, CLASS_Term, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Token"), FLAG_Token, CLASS_Token, CLASS_Term, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Stmt"), FLAG_Stmt, CLASS_Stmt, CLASS_Term, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Gamma"), FLAG_Gamma, CLASS_Gamma, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.BasicBlock"), FLAG_BasicBlock, CLASS_BasicBlock, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.KLRCode"), FLAG_KLRCode, CLASS_KLRCode, CLASS_Object, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Tvoid"), FLAG_Tvoid, CLASS_Any, CLASS_Any, 0 + 0 /*0*/,
	DATA_CLASS, _DATA("konoha.Tvar"), FLAG_Tvar, CLASS_Any, CLASS_Any, 0 + 0 /*0*/,
	DATA_GENERICS/*PairSS*/, CLASS_Tuple, 2, 0, TYPE_String, FN_, TYPE_String, FN_,
	DATA_GENERICS/*PairST1*/, CLASS_Tuple, 2, 0, TYPE_String, FN_, TYPE_T1, FN_,
	DATA_GENERICS/*PairT1T2*/, CLASS_Tuple, 2, 0, TYPE_T1, FN_, TYPE_T2, FN_,
	DATA_GENERICS/*Cmpr*/, CLASS_Func, 2, 1, TYPE_T1, FN_, TYPE_T1, FN_, TYPE_Int, FN_,
	DATA_GENERICS/*StringITR*/, CLASS_Iterator, 1, 0, TYPE_String, FN_,
	DATA_GENERICS/*T1ITR*/, CLASS_Iterator, 1, 0, TYPE_T1, FN_,
	DATA_GENERICS/*ThisITR*/, CLASS_Iterator, 1, 0, TYPE_This, FN_,
	DATA_GENERICS/*StringARRAY*/, CLASS_Array, 1, 0, TYPE_String, FN_,
	DATA_EXPT, _DATA("Exception"), 0, EBI_Exception, EBI_Exception, 
	DATA_EXPT, _DATA("Fatal"), 0, EBI_Fatal, EBI_Exception, 
	DATA_EXPT, _DATA("OutOfMemory"), 0, EBI_OutOfMemory, EBI_Fatal, 
	DATA_EXPT, _DATA("Security"), 0, EBI_Security, EBI_Exception, 
	DATA_EXPT, _DATA("Null"), 0, EBI_Null, EBI_Exception, 
	DATA_EXPT, _DATA("OutOfIndex"), 0, EBI_OutOfIndex, EBI_Exception, 
	DATA_EXPT, _DATA("IO"), 0, EBI_IO, EBI_Exception, 
	DATA_EXPT, _DATA("Script"), 0, EBI_Script, EBI_Exception, 
	DATA_EXPT, _DATA("Syntax"), 0, EBI_Syntax, EBI_Script, 
	DATA_EXPT, _DATA("Type"), 0, EBI_Type, EBI_Script, 
	DATA_EXPT, _DATA("Assertion"), 0, EBI_Assertion, EBI_Script, 
	0
};

static knh_FieldNameData0_t FieldNameData0[] = {
	{"", FN_},
	{"abstract", FN_abstract},
	{"add", FN_add},
	{"all", FN_all},
	{"aSCII", FN_aSCII},
	{"autoFlush", FN_autoFlush},
	{"bag", FN_bag},
	{"base", FN_base},
	{"bits", FN_bits},
	{"buf", FN_buf},
	{"c", FN_c},
	{"ch", FN_ch},
	{"char", FN_char},
	{"charset", FN_charset},
	{"class", FN_class},
	{"clearBuffer", FN_clearBuffer},
	{"close", FN_close},
	{"closed", FN_closed},
	{"const", FN_const},
	{"convert", FN_convert},
	{"d", FN_d},
	{"data", FN_data},
	{"debug", FN_debug},
	{"decode", FN_decode},
	{"defined", FN_defined},
	{"delegate", FN_delegate},
	{"dump", FN_dump},
	{"e", FN_e},
	{"empty", FN_empty},
	{"enc", FN_enc},
	{"encode", FN_encode},
	{"endsWith", FN_endsWith},
	{"equals", FN_equals},
	{"err", FN_err},
	{"event", FN_event},
	{"exec", FN_exec},
	{"f", FN_f},
	{"flag", FN_flag},
	{"float", FN_float},
	{"flush", FN_flush},
	{"fmt", FN_fmt},
	{"format", FN_format},
	{"gc", FN_gc},
	{"hashCode", FN_hashCode},
	{"in", FN_in},
	{"indexOf", FN_indexOf},
	{"init", FN_init},
	{"initCapacity", FN_initCapacity},
	{"int", FN_int},
	{"invoke", FN_invoke},
	{"it", FN_it},
	{"jITCode", FN_jITCode},
	{"k", FN_k},
	{"key", FN_key},
	{"lastIndexOf", FN_lastIndexOf},
	{"length", FN_length},
	{"likely", FN_likely},
	{"listProperties", FN_listProperties},
	{"main", FN_main},
	{"man", FN_man},
	{"match", FN_match},
	{"method", FN_method},
	{"mode", FN_mode},
	{"msg", FN_msg},
	{"n", FN_n},
	{"name", FN_name},
	{"new", FN_new},
	{"new:ARRAY", FN_new__ARRAY},
	{"new:LIST", FN_new__LIST},
	{"new:MAP", FN_new__MAP},
	{"next", FN_next},
	{"notNull", FN_notNull},
	{"ns", FN_ns},
	{"null", FN_null},
	{"offset", FN_offset},
	{"option", FN_option},
	{"out", FN_out},
	{"p", FN_p},
	{"path", FN_path},
	{"pattern", FN_pattern},
	{"print", FN_print},
	{"println", FN_println},
	{"property", FN_property},
	{"putc", FN_putc},
	{"qualifier", FN_qualifier},
	{"query", FN_query},
	{"random", FN_random},
	{"randomSeed", FN_randomSeed},
	{"re", FN_re},
	{"read", FN_read},
	{"readLine", FN_readLine},
	{"remove", FN_remove},
	{"replace", FN_replace},
	{"s", FN_s},
	{"search", FN_search},
	{"seed", FN_seed},
	{"size", FN_size},
	{"split", FN_split},
	{"startsWith", FN_startsWith},
	{"string", FN_string},
	{"substring", FN_substring},
	{"super", FN_super},
	{"this", FN_this},
	{"time", FN_time},
	{"trim", FN_trim},
	{"u", FN_u},
	{"unlikely", FN_unlikely},
	{"urn", FN_urn},
	{"v", FN_v},
	{"value", FN_value},
	{"vargs", FN_vargs},
	{"verbose", FN_verbose},
	{"write", FN_write},
	{"writeChar", FN_writeChar},
	{"writeData", FN_writeData},
	{"x", FN_x},
	{NULL}
};

static knh_data_t ParamArrayData0[] = {
	DATA_PARAM/*0*/, 0, 0, 0, 
	DATA_PARAM/*1*/, 0, 1, 0, TYPE_Int, FN_char,
	DATA_PARAM/*2*/, 0, 3, 0, TYPE_Bytes, FN_buf, TYPE_Int, FN_offset, TYPE_Int, FN_length,
	DATA_PARAM/*3*/, 0, 1, 1, TYPE_Int, FN_n, TYPE_T1, FN_return,
	DATA_PARAM/*4*/, 0, 2, 1, TYPE_Int, FN_n, TYPE_T1, FN_v, TYPE_T1, FN_return,
	DATA_PARAM/*5*/, 0, 1, 1, TYPE_T1, FN_v, TYPE_T1, FN_return,
	DATA_PARAM/*6*/, FLAG_ParamArray_VARGs, 1, 0, TYPE_T1, FN_value,
	DATA_PARAM/*7*/, 0, 1, 1, TYPE_String, FN_urn, TYPE_This, FN_return,
	DATA_PARAM/*8*/, 0, 1, 1, TYPE_String, FN_query, TYPE_ResultSet, FN_return,
	DATA_PARAM/*9*/, 0, 1, 0, TYPE_String, FN_query,
	DATA_PARAM/*10*/, 0, 0, 1, TYPE_Int, FN_return,
	DATA_PARAM/*11*/, 0, 0, 1, TYPE_Boolean, FN_return,
	DATA_PARAM/*12*/, 0, 1, 1, TYPE_Int, FN_n, TYPE_String, FN_return,
	DATA_PARAM/*13*/, 0, 1, 1, TYPE_Any, FN_n, TYPE_Int, FN_return,
	DATA_PARAM/*14*/, 0, 1, 1, TYPE_Any, FN_n, TYPE_Float, FN_return,
	DATA_PARAM/*15*/, 0, 1, 1, TYPE_Any, FN_n, TYPE_String, FN_return,
	DATA_PARAM/*16*/, 0, 1, 1, TYPE_Any, FN_n, TYPE_Any, FN_return,
	DATA_PARAM/*17*/, 0, 1, 1, TYPE_T1, FN_key, TYPE_Boolean, FN_return,
	DATA_PARAM/*18*/, 0, 1, 1, TYPE_T1, FN_key, TYPE_T2, FN_return,
	DATA_PARAM/*19*/, 0, 2, 0, TYPE_T1, FN_key, TYPE_T2, FN_value,
	DATA_PARAM/*20*/, 0, 1, 0, TYPE_T1, FN_key,
	DATA_PARAM/*21*/, 0, 1, 1, TYPE_String, FN_fmt, TYPE_String, FN_return,
	DATA_PARAM/*22*/, 0, 0, 1, TYPE_StringITR, FN_return,
	DATA_PARAM/*23*/, 0, 0, 1, TYPE_T1ITR, FN_return,
	DATA_PARAM/*24*/, 0, 0, 1, TYPE_ThisITR, FN_return,
	DATA_PARAM/*25*/, 0, 0, 1, TYPE_This, FN_return,
	DATA_PARAM/*26*/, FLAG_ParamArray_VARGs, 1, 1, TYPE_Any, FN_value, TYPE_This, FN_return,
	DATA_PARAM/*27*/, 0, 1, 1, TYPE_Int, FN_init, TYPE_Bytes, FN_return,
	DATA_PARAM/*28*/, 0, 2, 1, TYPE_Bytes, FN_buf, TYPE_StringDecoder, FN_c, TYPE_String, FN_return,
	DATA_PARAM/*29*/, 0, 3, 1, TYPE_String, FN_pattern, TYPE_String, FN_option, TYPE_NameSpace, FN_ns, TYPE_Regex, FN_return,
	DATA_PARAM/*30*/, 0, 1, 1, TYPE_Int, FN_initCapacity, TYPE_This, FN_return,
	DATA_PARAM/*31*/, 0, 1, 1, TYPE_Int, FN_size, TYPE_This, FN_return,
	DATA_PARAM/*32*/, FLAG_ParamArray_VARGs, 1, 1, TYPE_T1, FN_value, TYPE_This, FN_return,
	DATA_PARAM/*33*/, 0, 2, 1, TYPE_Int, FN_init, TYPE_String, FN_path, TYPE_This, FN_return,
	DATA_PARAM/*34*/, 0, 3, 1, TYPE_String, FN_event, TYPE_String, FN_msg, TYPE_Any, FN_bag, TYPE_Exception, FN_return,
	DATA_PARAM/*35*/, 0, 2, 1, TYPE_Any, FN_base, TYPE_Method, FN_method, TYPE_This, FN_return,
	DATA_PARAM/*36*/, 0, 1, 0, TYPE_Int, FN_seed,
	DATA_PARAM/*37*/, 0, 1, 1, TYPE_Int, FN_n, TYPE_Int, FN_return,
	DATA_PARAM/*38*/, 0, 0, 1, TYPE_Float, FN_return,
	DATA_PARAM/*39*/, 0, 0, 1, TYPE_Class, FN_return,
	DATA_PARAM/*40*/, 0, 0, 1, TYPE_String, FN_return,
	DATA_PARAM/*41*/, 0, 1, 1, TYPE_Any, FN_x, TYPE_Any, FN_return,
	DATA_PARAM/*42*/, 0, 1, 1, TYPE_Class, FN_c, TYPE_Boolean, FN_return,
	DATA_PARAM/*43*/, 0, 1, 1, TYPE_Any, FN_value, TYPE_Boolean, FN_return,
	DATA_PARAM/*44*/, 0, 1, 1, TYPE_Int, FN_value, TYPE_Boolean, FN_return,
	DATA_PARAM/*45*/, 0, 1, 1, TYPE_Float, FN_value, TYPE_Boolean, FN_return,
	DATA_PARAM/*46*/, 0, 1, 1, TYPE_String, FN_s, TYPE_Boolean, FN_return,
	DATA_PARAM/*47*/, 0, 1, 1, TYPE_Any, FN_v, TYPE_Boolean, FN_return,
	DATA_PARAM/*48*/, 0, 1, 1, TYPE_Int, FN_v, TYPE_Int, FN_return,
	DATA_PARAM/*49*/, 0, 1, 1, TYPE_Float, FN_v, TYPE_Float, FN_return,
	DATA_PARAM/*50*/, 0, 1, 1, TYPE_Float, FN_n, TYPE_Float, FN_return,
	DATA_PARAM/*51*/, 0, 1, 1, TYPE_String, FN_s, TYPE_String, FN_return,
	DATA_PARAM/*52*/, 0, 1, 1, TYPE_Any, FN_value, TYPE_Any, FN_return,
	DATA_PARAM/*53*/, 0, 0, 1, TYPE_Any, FN_return,
	DATA_PARAM/*54*/, FLAG_ParamArray_VARGs, 1, 1, TYPE_Int, FN_n, TYPE_Int, FN_return,
	DATA_PARAM/*55*/, 0, 2, 1, TYPE_Int, FN_n, TYPE_Int, FN_c, TYPE_Int, FN_return,
	DATA_PARAM/*56*/, 0, 1, 0, TYPE_Int, FN_c,
	DATA_PARAM/*57*/, 0, 2, 1, TYPE_Int, FN_s, TYPE_Int, FN_e, TYPE_Bytes, FN_return,
	DATA_PARAM/*58*/, 0, 2, 1, TYPE_Int, FN_offset, TYPE_Int, FN_length, TYPE_String, FN_return,
	DATA_PARAM/*59*/, 0, 2, 1, TYPE_Int, FN_s, TYPE_Int, FN_e, TYPE_String, FN_return,
	DATA_PARAM/*60*/, 0, 2, 1, TYPE_Int, FN_s, TYPE_Int, FN_e, TYPE_This, FN_return,
	DATA_PARAM/*61*/, 0, 2, 1, TYPE_String, FN_urn, TYPE_String, FN_mode, TYPE_InputStream, FN_return,
	DATA_PARAM/*62*/, 0, 3, 1, TYPE_Bytes, FN_buf, TYPE_Int, FN_offset, TYPE_Int, FN_length, TYPE_Int, FN_return,
	DATA_PARAM/*63*/, 0, 1, 1, TYPE_StringDecoder, FN_c, TYPE_StringDecoder, FN_return,
	DATA_PARAM/*64*/, 0, 2, 1, TYPE_String, FN_urn, TYPE_String, FN_mode, TYPE_OutputStream, FN_return,
	DATA_PARAM/*65*/, 0, 1, 0, TYPE_Int, FN_ch,
	DATA_PARAM/*66*/, FLAG_ParamArray_VARGs, 1, 0, TYPE_Object, FN_value,
	DATA_PARAM/*67*/, FLAG_ParamArray_VARGs, 1, 0, TYPE_String, FN_s,
	DATA_PARAM/*68*/, FLAG_ParamArray_VARGs, 1, 0, TYPE_Any, FN_value,
	DATA_PARAM/*69*/, FLAG_ParamArray_VARGs, 1, 0, TYPE_Object, FN_data,
	DATA_PARAM/*70*/, 0, 1, 1, TYPE_StringEncoder, FN_c, TYPE_StringEncoder, FN_return,
	DATA_PARAM/*71*/, 0, 1, 1, TYPE_NameSpace, FN_ns, TYPE_Boolean, FN_return,
	DATA_PARAM/*72*/, 0, 3, 1, TYPE_String, FN_qualifier, TYPE_NameSpace, FN_ns, TYPE_Class, FN_c, TYPE_Any, FN_return,
	DATA_PARAM/*73*/, 0, 1, 1, TYPE_String, FN_s, TYPE_Int, FN_return,
	DATA_PARAM/*74*/, 0, 1, 1, TYPE_Regex, FN_re, TYPE_Int, FN_return,
	DATA_PARAM/*75*/, 0, 1, 1, TYPE_Regex, FN_re, TYPE_StringARRAY, FN_return,
	DATA_PARAM/*76*/, 0, 2, 1, TYPE_Regex, FN_re, TYPE_String, FN_s, TYPE_String, FN_return,
	DATA_PARAM/*77*/, 0, 1, 1, TYPE_Converter, FN_enc, TYPE_Bytes, FN_return,
	DATA_PARAM/*78*/, 0, 1, 1, TYPE_StringEncoder, FN_enc, TYPE_Bytes, FN_return,
	DATA_PARAM/*79*/, 0, 1, 1, TYPE_StringDecoder, FN_c, TYPE_String, FN_return,
	DATA_PARAM/*80*/, 0, 1, 1, TYPE_StringConverter, FN_c, TYPE_String, FN_return,
	DATA_PARAM/*81*/, 0, 0, 1, TYPE_InputStream, FN_return,
	DATA_PARAM/*82*/, 0, 0, 1, TYPE_OutputStream, FN_return,
	DATA_PARAM/*83*/, 0, 1, 1, TYPE_String, FN_key, TYPE_Any, FN_return,
	DATA_PARAM/*84*/, 0, 2, 1, TYPE_String, FN_key, TYPE_Any, FN_value, TYPE_Any, FN_return,
	DATA_PARAM/*85*/, 0, 1, 1, TYPE_String, FN_key, TYPE_StringARRAY, FN_return,
	DATA_PARAM/*86*/, 0, 1, 1, TYPE_InputStream, FN_in, TYPE_InputStream, FN_return,
	DATA_PARAM/*87*/, 0, 1, 1, TYPE_OutputStream, FN_out, TYPE_OutputStream, FN_return,
	DATA_PARAM/*88*/, 0, 1, 1, TYPE_String, FN_event, TYPE_Boolean, FN_return,
	DATA_PARAM/*89*/, 0, 2, 1, TYPE_String, FN_name, TYPE_Object, FN_value, TYPE_Any, FN_return,
	DATA_PARAM/*90*/, 0, 1, 1, TYPE_Boolean, FN_flag, TYPE_Boolean, FN_return,
	0
};
#define K_PARAM0_SIZE                   91

static knh_data_t APIData0[] = {
	DATA_METHOD0, CLASS_Bytes, MN_putc, 0, _DATA(Bytes_putc), /*P=*/1,
	DATA_METHOD0, CLASS_Bytes, MN_write, 0, _DATA(Bytes_write), /*P=*/2,
	DATA_METHOD0, CLASS_Bytes, MN_add, 0, _DATA(Bytes_write), /*P=*/2,
	DATA_METHOD0, CLASS_Array, MN_get, 0, _DATA(Array_get), /*P=*/3,
	DATA_METHOD0, CLASS_Array, MN_set, 0, _DATA(Array_set), /*P=*/4,
	DATA_METHOD0, CLASS_Array, MN_setAll, 0, _DATA(Array_setAll), /*P=*/5,
	DATA_METHOD0, CLASS_Array, MN_add, 0, _DATA(Array_add), /*P=*/6,
	DATA_METHOD0, CLASS_Array, MN_opSEND, 0, _DATA(Array_add), /*P=*/6,
	DATA_METHOD0, CLASS_Func, MN_setJITCode, 0, _DATA(Func_setJITCode), /*P=*/0,
	DATA_METHOD0, CLASS_Connection, MN_new, 0, _DATA(Connection_new), /*P=*/7,
	DATA_METHOD0, CLASS_Connection, MN_query, 0, _DATA(Connection_query), /*P=*/8,
	DATA_METHOD0, CLASS_Connection, MN_exec, 0, _DATA(Connection_exec), /*P=*/9,
	DATA_METHOD0, CLASS_Connection, MN_close, 0, _DATA(Connection_close), /*P=*/0,
	DATA_METHOD0, CLASS_ResultSet, MN_getSize, 0, _DATA(ResultSet_getSize), /*P=*/10,
	DATA_METHOD0, CLASS_ResultSet, MN_next, 0, _DATA(ResultSet_next), /*P=*/11,
	DATA_METHOD0, CLASS_ResultSet, MN_getName, 0, _DATA(ResultSet_getName), /*P=*/12,
	DATA_METHOD0, CLASS_ResultSet, MN_getInt, 0, _DATA(ResultSet_getInt), /*P=*/13,
	DATA_METHOD0, CLASS_ResultSet, MN_getFloat, 0, _DATA(ResultSet_getFloat), /*P=*/14,
	DATA_METHOD0, CLASS_ResultSet, MN_getString, 0, _DATA(ResultSet_getString), /*P=*/15,
	DATA_METHOD0, CLASS_ResultSet, MN_get, 0, _DATA(ResultSet_get), /*P=*/16,
	DATA_METHOD0, CLASS_ResultSet, MN_close, 0, _DATA(ResultSet_close), /*P=*/0,
	DATA_METHOD0, CLASS_Map, MN_opHAS, 0, _DATA(Map_opHAS), /*P=*/17,
	DATA_METHOD0, CLASS_Map, MN_get, 0, _DATA(Map_get), /*P=*/18,
	DATA_METHOD0, CLASS_Map, MN_set, 0, _DATA(DictMap_set), /*P=*/19,
	DATA_METHOD0, CLASS_Map, MN_remove, 0, _DATA(DictMap_remove), /*P=*/20,
	DATA_METHOD0, CLASS_Int, MN_format, FLAG_Method_Const, _DATA(Int_format), /*P=*/21,
	DATA_METHOD0, CLASS_Float, MN_format, FLAG_Method_Const, _DATA(Float_format), /*P=*/21,
	DATA_METHOD0, CLASS_String, MN_format, FLAG_Method_Const, _DATA(String_format), /*P=*/21,
	DATA_METHOD0, CLASS_Object, MN__empty, 0, _DATA(Object__empty), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__s, 0, _DATA(Object__s), /*P=*/0,
	DATA_METHOD0, CLASS_Boolean, MN__s, 0, _DATA(Boolean__s), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__s, 0, _DATA(Int__s), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__d, 0, _DATA(Int__s), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__s, 0, _DATA(Float__s), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__f, 0, _DATA(Float__s), /*P=*/0,
	DATA_METHOD0, CLASS_String, MN__s, 0, _DATA(String__s), /*P=*/0,
	DATA_METHOD0, CLASS_Bytes, MN__s, 0, _DATA(Bytes__s), /*P=*/0,
	DATA_METHOD0, CLASS_Regex, MN__s, 0, _DATA(Regex__s), /*P=*/0,
	DATA_METHOD0, CLASS_Class, MN__s, 0, _DATA(Class__s), /*P=*/0,
	DATA_METHOD0, CLASS_Method, MN__s, 0, _DATA(Method__s), /*P=*/0,
	DATA_METHOD0, CLASS_Exception, MN__s, 0, _DATA(Exception__s), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__k, 0, _DATA(Object__k), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__k, 0, _DATA(Int__k), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__k, 0, _DATA(Float__k), /*P=*/0,
	DATA_METHOD0, CLASS_String, MN__k, 0, _DATA(String__k), /*P=*/0,
	DATA_METHOD0, CLASS_Iterator, MN__k, 0, _DATA(Iterator__k), /*P=*/0,
	DATA_METHOD0, CLASS_Array, MN__k, 0, _DATA(Array__k), /*P=*/0,
	DATA_METHOD0, CLASS_Map, MN__k, 0, _DATA(Map__k), /*P=*/0,
	DATA_METHOD0, CLASS_Class, MN__k, 0, _DATA(Class__k), /*P=*/0,
	DATA_METHOD0, CLASS_Method, MN__k, 0, _DATA(Method__k), /*P=*/0,
	DATA_METHOD0, CLASS_Translator, MN__k, 0, _DATA(Translator__k), /*P=*/0,
	DATA_METHOD0, CLASS_InputStream, MN__k, 0, _DATA(InputStream__k), /*P=*/0,
	DATA_METHOD0, CLASS_OutputStream, MN__k, 0, _DATA(OutputStream__k), /*P=*/0,
	DATA_METHOD0, CLASS_Script, MN__k, 0, _DATA(Script__k), /*P=*/0,
	DATA_METHOD0, CLASS_Any, MN__s, 0, _DATA(Any__k), /*P=*/0,
	DATA_METHOD0, CLASS_Func, MN__data, 0, _DATA(Func__data), /*P=*/0,
	DATA_METHOD0, CLASS_Bytes, MN__dump, 0, _DATA(Bytes__dump), /*P=*/0,
	DATA_METHOD0, CLASS_Method, MN__dump, 0, _DATA(Method__dump), /*P=*/0,
	DATA_METHOD0, CLASS_Exception, MN__dump, 0, _DATA(Exception__dump), /*P=*/0,
	DATA_METHOD0, CLASS_Class, MN__man, 0, _DATA(Class__man), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__man, 0, _DATA(Class__man), /*P=*/0,
	DATA_METHOD0, CLASS_Object, MN__p, 0, _DATA(Object__p), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__c, 0, _DATA(Int__c), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__u, 0, _DATA(Int__u), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__f, 0, _DATA(Int__f), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__x, 0, _DATA(Int__x), /*P=*/0,
	DATA_METHOD0, CLASS_Int, MN__bits, 0, _DATA(Int__bits), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__d, 0, _DATA(Float__d), /*P=*/0,
	DATA_METHOD0, CLASS_Float, MN__bits, 0, _DATA(Float__bits), /*P=*/0,
	DATA_METHOD0, CLASS_String, MN_opITR, 0, _DATA(String_Iterator), /*P=*/22,
	DATA_METHOD0, CLASS_Array, MN_opITR, 0, _DATA(Array_Iterator), /*P=*/23,
	DATA_METHOD0, CLASS_Map, MN_opITR, 0, _DATA(DictMap_String__), /*P=*/22,
	DATA_METHOD0, CLASS_Object, MN_opITR, 0, _DATA(Object_Iterator), /*P=*/24,
	DATA_METHOD0, CLASS_Object, MN_new, FLAG_Method_Virtual, _DATA(Object_new), /*P=*/25,
	DATA_METHOD0, CLASS_Object, MN_new__MAP, FLAG_Method_Hidden, _DATA(Object_new__MAP), /*P=*/26,
	DATA_METHOD0, CLASS_Bytes, MN_new, 0, _DATA(Bytes_new), /*P=*/27,
	DATA_METHOD0, CLASS_Bytes, MN_new__ARRAY, 0, _DATA(Bytes_new__ARRAY), /*P=*/27,
	DATA_METHOD0, CLASS_String, MN_new, 0, _DATA(String_new), /*P=*/28,
	DATA_METHOD0, CLASS_Regex, MN_new, FLAG_Method_Const, _DATA(Regex_new), /*P=*/29,
	DATA_METHOD0, CLASS_Array, MN_new, 0, _DATA(Array_new), /*P=*/30,
	DATA_METHOD0, CLASS_Array, MN_new__ARRAY, FLAG_Method_Hidden, _DATA(Array_new__ARRAY), /*P=*/31,
	DATA_METHOD0, CLASS_Array, MN_new__LIST, FLAG_Method_Hidden, _DATA(Array_new__LIST), /*P=*/32,
	DATA_METHOD0, CLASS_Map, MN_new, 0, _DATA(Map_new), /*P=*/33,
	DATA_METHOD0, CLASS_Map, MN_new__MAP, FLAG_Method_Hidden, _DATA(Map_new__MAP), /*P=*/32,
	DATA_METHOD0, CLASS_Exception, MN_new, 0, _DATA(Exception_new), /*P=*/34,
	DATA_METHOD0, CLASS_Func, MN_new, 0, _DATA(Func_new), /*P=*/35,
	DATA_METHOD0, CLASS_System, MN_setRandomSeed, FLAG_Method_Static, _DATA(System_setRandomSeed), /*P=*/36,
	DATA_METHOD0, CLASS_Int, MN_random, FLAG_Method_Static, _DATA(Int_random), /*P=*/37,
	DATA_METHOD0, CLASS_Float, MN_random, FLAG_Method_Static, _DATA(Float_random), /*P=*/38,
	DATA_METHOD0, CLASS_Object, MN_getClass, FLAG_Method_Const, _DATA(Object_getClass), /*P=*/39,
	DATA_METHOD0, CLASS_Object, MN_hashCode, 0, _DATA(Object_hashCode), /*P=*/10,
	DATA_METHOD0, CLASS_Object, MN_isNull, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Object_isNull), /*P=*/11,
	DATA_METHOD0, CLASS_Object, MN_isNotNull, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Object_isNotNull), /*P=*/11,
	DATA_METHOD0, CLASS_Object, MN_getKey, FLAG_Method_Const|FLAG_Method_Virtual, _DATA(Object_getKey), /*P=*/40,
	DATA_METHOD0, CLASS_Method, MN_isAbstract, FLAG_Method_Const, _DATA(Method_isAbstract), /*P=*/11,
	DATA_METHOD0, CLASS_Method, MN_getName, FLAG_Method_Const, _DATA(Method_getName), /*P=*/40,
	DATA_METHOD0, CLASS_Func, MN_invoke, FLAG_Method_Hidden|FLAG_Method_Private, _DATA(Func_invoke), /*P=*/41,
	DATA_METHOD0, CLASS_Object, MN_opADDR, FLAG_Method_Const, _DATA(Object_opADDR), /*P=*/10,
	DATA_METHOD0, CLASS_Object, MN_opOF, FLAG_Method_Const, _DATA(Object_opOF), /*P=*/42,
	DATA_METHOD0, CLASS_Object, MN_opEQ, FLAG_Method_Const, _DATA(Object_opEQ), /*P=*/43,
	DATA_METHOD0, CLASS_Object, MN_opNOTEQ, FLAG_Method_Const, _DATA(Object_opNOTEQ), /*P=*/43,
	DATA_METHOD0, CLASS_Object, MN_opLT, FLAG_Method_Const, _DATA(Object_opLT), /*P=*/43,
	DATA_METHOD0, CLASS_Object, MN_opLTE, FLAG_Method_Const, _DATA(Object_opLTE), /*P=*/43,
	DATA_METHOD0, CLASS_Object, MN_opGT, FLAG_Method_Const, _DATA(Object_opGT), /*P=*/43,
	DATA_METHOD0, CLASS_Object, MN_opGTE, FLAG_Method_Const, _DATA(Object_opGTE), /*P=*/43,
	DATA_METHOD0, CLASS_Int, MN_opEQ, FLAG_Method_Const, _DATA(Int_opEQ), /*P=*/44,
	DATA_METHOD0, CLASS_Int, MN_opNOTEQ, FLAG_Method_Const, _DATA(Int_opNOTEQ), /*P=*/44,
	DATA_METHOD0, CLASS_Int, MN_opLT, FLAG_Method_Const, _DATA(Int_opLT), /*P=*/44,
	DATA_METHOD0, CLASS_Int, MN_opLTE, FLAG_Method_Const, _DATA(Int_opLTE), /*P=*/44,
	DATA_METHOD0, CLASS_Int, MN_opGT, FLAG_Method_Const, _DATA(Int_opGT), /*P=*/44,
	DATA_METHOD0, CLASS_Int, MN_opGTE, FLAG_Method_Const, _DATA(Int_opGTE), /*P=*/44,
	DATA_METHOD0, CLASS_Float, MN_opEQ, FLAG_Method_Const, _DATA(Float_opEQ), /*P=*/45,
	DATA_METHOD0, CLASS_Float, MN_opNOTEQ, FLAG_Method_Const, _DATA(Float_opNOTEQ), /*P=*/45,
	DATA_METHOD0, CLASS_Float, MN_opLT, FLAG_Method_Const, _DATA(Float_opLT), /*P=*/45,
	DATA_METHOD0, CLASS_Float, MN_opLTE, FLAG_Method_Const, _DATA(Float_opLTE), /*P=*/45,
	DATA_METHOD0, CLASS_Float, MN_opGT, FLAG_Method_Const, _DATA(Float_opGT), /*P=*/45,
	DATA_METHOD0, CLASS_Float, MN_opGTE, FLAG_Method_Const, _DATA(Float_opGTE), /*P=*/45,
	DATA_METHOD0, CLASS_String, MN_opHAS, FLAG_Method_Const, _DATA(String_opHAS), /*P=*/46,
	DATA_METHOD0, CLASS_Array, MN_opHAS, 0, _DATA(Array_opHAS), /*P=*/47,
	DATA_METHOD0, CLASS_Object, MN_opIS, FLAG_Method_Const, _DATA(Object_opIS), /*P=*/47,
	DATA_METHOD0, CLASS_Int, MN_opADD, FLAG_Method_Const, _DATA(Int_opADD), /*P=*/48,
	DATA_METHOD0, CLASS_Int, MN_opNEG, FLAG_Method_Const, _DATA(Int_opNEG), /*P=*/10,
	DATA_METHOD0, CLASS_Int, MN_opSUB, FLAG_Method_Const, _DATA(Int_opSUB), /*P=*/37,
	DATA_METHOD0, CLASS_Int, MN_opMUL, FLAG_Method_Const, _DATA(Int_opMUL), /*P=*/37,
	DATA_METHOD0, CLASS_Int, MN_opDIV, FLAG_Method_Const, _DATA(Int_opDIV), /*P=*/37,
	DATA_METHOD0, CLASS_Int, MN_opMOD, FLAG_Method_Const, _DATA(Int_opMOD), /*P=*/37,
	DATA_METHOD0, CLASS_Float, MN_opADD, FLAG_Method_Const, _DATA(Float_opADD), /*P=*/49,
	DATA_METHOD0, CLASS_Float, MN_opNEG, FLAG_Method_Const, _DATA(Float_opNEG), /*P=*/38,
	DATA_METHOD0, CLASS_Float, MN_opSUB, FLAG_Method_Const, _DATA(Float_opSUB), /*P=*/50,
	DATA_METHOD0, CLASS_Float, MN_opMUL, FLAG_Method_Const, _DATA(Float_opMUL), /*P=*/50,
	DATA_METHOD0, CLASS_Float, MN_opDIV, FLAG_Method_Const, _DATA(Float_opDIV), /*P=*/50,
	DATA_METHOD0, CLASS_String, MN_opSUB, FLAG_Method_Const, _DATA(String_opSUB), /*P=*/51,
	DATA_METHOD0, CLASS_Any, MN_opADD, 0, _DATA(Any_opADD), /*P=*/52,
	DATA_METHOD0, CLASS_Any, MN_opSUB, 0, _DATA(Any_opADD), /*P=*/52,
	DATA_METHOD0, CLASS_Any, MN_opMUL, 0, _DATA(Any_opADD), /*P=*/52,
	DATA_METHOD0, CLASS_Any, MN_opDIV, 0, _DATA(Any_opADD), /*P=*/52,
	DATA_METHOD0, CLASS_Any, MN_opMOD, 0, _DATA(Any_opADD), /*P=*/52,
	DATA_METHOD0, CLASS_Any, MN_opNEG, 0, _DATA(Any_opADD), /*P=*/53,
	DATA_METHOD0, CLASS_Boolean, MN_opNOT, FLAG_Method_Const, _DATA(Boolean_opNOT), /*P=*/11,
	DATA_METHOD0, CLASS_Int, MN_opLAND, FLAG_Method_Const, _DATA(Int_opLAND), /*P=*/54,
	DATA_METHOD0, CLASS_Int, MN_opLOR, FLAG_Method_Const, _DATA(Int_opLOR), /*P=*/54,
	DATA_METHOD0, CLASS_Int, MN_opLXOR, FLAG_Method_Const, _DATA(Int_opLXOR), /*P=*/37,
	DATA_METHOD0, CLASS_Int, MN_opLNOT, FLAG_Method_Const, _DATA(Int_opLNOT), /*P=*/10,
	DATA_METHOD0, CLASS_Int, MN_opLSFT, FLAG_Method_Const, _DATA(Int_opLSFT), /*P=*/37,
	DATA_METHOD0, CLASS_Int, MN_opRSFT, FLAG_Method_Const, _DATA(Int_opRSFT), /*P=*/37,
	DATA_METHOD0, CLASS_Bytes, MN_getSize, 0, _DATA(Bytes_getSize), /*P=*/10,
	DATA_METHOD0, CLASS_Array, MN_getSize, 0, _DATA(Bytes_getSize), /*P=*/10,
	DATA_METHOD0, CLASS_String, MN_getSize, FLAG_Method_Const, _DATA(String_getSize), /*P=*/10,
	DATA_METHOD0, CLASS_Map, MN_getSize, 0, _DATA(Map_getSize), /*P=*/10,
	DATA_METHOD0, CLASS_Bytes, MN_get, 0, _DATA(Bytes_get), /*P=*/37,
	DATA_METHOD0, CLASS_Bytes, MN_set, 0, _DATA(Bytes_set), /*P=*/55,
	DATA_METHOD0, CLASS_Bytes, MN_setAll, 0, _DATA(Bytes_setAll), /*P=*/56,
	DATA_METHOD0, CLASS_String, MN_get, FLAG_Method_Const, _DATA(String_get), /*P=*/12,
	DATA_METHOD0, CLASS_Bytes, MN_opUNTIL, 0, _DATA(Bytes_opUNTIL), /*P=*/57,
	DATA_METHOD0, CLASS_Bytes, MN_opTO, 0, _DATA(Bytes_opTO), /*P=*/57,
	DATA_METHOD0, CLASS_String, MN_substring, FLAG_Method_Const, _DATA(String_substring), /*P=*/58,
	DATA_METHOD0, CLASS_String, MN_opUNTIL, FLAG_Method_Const, _DATA(String_opUNTIL), /*P=*/59,
	DATA_METHOD0, CLASS_String, MN_opTO, FLAG_Method_Const, _DATA(String_opTO), /*P=*/59,
	DATA_METHOD0, CLASS_Array, MN_opUNTIL, 0, _DATA(Array_opUNTIL), /*P=*/60,
	DATA_METHOD0, CLASS_Array, MN_opTO, 0, _DATA(Array_opTO), /*P=*/60,
	DATA_METHOD0, CLASS_InputStream, MN_new, 0, _DATA(InputStream_new), /*P=*/61,
	DATA_METHOD0, CLASS_InputStream, MN_getChar, 0, _DATA(InputStream_getChar), /*P=*/10,
	DATA_METHOD0, CLASS_InputStream, MN_read, 0, _DATA(InputStream_read), /*P=*/62,
	DATA_METHOD0, CLASS_InputStream, MN_isClosed, 0, _DATA(InputStream_isClosed), /*P=*/11,
	DATA_METHOD0, CLASS_InputStream, MN_close, 0, _DATA(InputStream_close), /*P=*/0,
	DATA_METHOD0, CLASS_InputStream, MN_setCharset, 0, _DATA(InputStream_setCharset), /*P=*/63,
	DATA_METHOD0, CLASS_InputStream, MN_readLine, 0, _DATA(InputStream_readLine), /*P=*/40,
	DATA_METHOD0, CLASS_OutputStream, MN_new, 0, _DATA(OutputStream_new), /*P=*/64,
	DATA_METHOD0, CLASS_OutputStream, MN_writeChar, 0, _DATA(OutputStream_writeChar), /*P=*/65,
	DATA_METHOD0, CLASS_OutputStream, MN_write, 0, _DATA(OutputStream_write), /*P=*/2,
	DATA_METHOD0, CLASS_OutputStream, MN_isClosed, 0, _DATA(OutputStream_isClosed), /*P=*/11,
	DATA_METHOD0, CLASS_OutputStream, MN_print, 0, _DATA(OutputStream_print), /*P=*/66,
	DATA_METHOD0, CLASS_OutputStream, MN_opSEND, 0, _DATA(OutputStream_opSEND), /*P=*/67,
	DATA_METHOD0, CLASS_OutputStream, MN_println, 0, _DATA(OutputStream_println), /*P=*/68,
	DATA_METHOD0, CLASS_OutputStream, MN_writeData, 0, _DATA(OutputStream_writeData), /*P=*/69,
	DATA_METHOD0, CLASS_OutputStream, MN_flush, 0, _DATA(OutputStream_flush), /*P=*/0,
	DATA_METHOD0, CLASS_OutputStream, MN_clearBuffer, 0, _DATA(OutputStream_clearBuffer), /*P=*/0,
	DATA_METHOD0, CLASS_OutputStream, MN_close, 0, _DATA(OutputStream_close), /*P=*/0,
	DATA_METHOD0, CLASS_OutputStream, MN_setCharset, 0, _DATA(OutputStream_setCharaset), /*P=*/70,
	DATA_METHOD0, CLASS_String, MN_opEXISTS, FLAG_Method_Const, _DATA(String_opEXISTS), /*P=*/71,
	DATA_METHOD0, CLASS_String, MN_path, FLAG_Method_Hidden|FLAG_Method_Private, _DATA(String_path), /*P=*/72,
	DATA_METHOD0, CLASS_String, MN_equals, FLAG_Method_Const, _DATA(String_equals), /*P=*/46,
	DATA_METHOD0, CLASS_String, MN_startsWith, FLAG_Method_Const, _DATA(String_startsWith), /*P=*/46,
	DATA_METHOD0, CLASS_String, MN_endsWith, FLAG_Method_Const, _DATA(String_endsWith), /*P=*/46,
	DATA_METHOD0, CLASS_String, MN_indexOf, FLAG_Method_Const, _DATA(String_indexOf), /*P=*/73,
	DATA_METHOD0, CLASS_String, MN_lastIndexOf, FLAG_Method_Const, _DATA(String_lastIndexOf), /*P=*/73,
	DATA_METHOD0, CLASS_String, MN_search, FLAG_Method_Const, _DATA(String_search), /*P=*/74,
	DATA_METHOD0, CLASS_String, MN_match, FLAG_Method_Const, _DATA(String_match), /*P=*/75,
	DATA_METHOD0, CLASS_String, MN_replace, FLAG_Method_Const, _DATA(String_replace), /*P=*/76,
	DATA_METHOD0, CLASS_String, MN_split, FLAG_Method_Const, _DATA(String_split), /*P=*/75,
	DATA_METHOD0, CLASS_Bytes, MN_, FLAG_Method_Const, _DATA(Bytes_convert), /*P=*/77,
	DATA_METHOD0, CLASS_String, MN_encode, FLAG_Method_Const, _DATA(String_encode), /*P=*/78,
	DATA_METHOD0, CLASS_Bytes, MN_decode, FLAG_Method_Const, _DATA(Bytes_toString), /*P=*/79,
	DATA_METHOD0, CLASS_String, MN_, FLAG_Method_Const, _DATA(String_convert), /*P=*/80,
	DATA_METHOD0, CLASS_String, MN_convert, FLAG_Method_Const, _DATA(String_convert), /*P=*/80,
	DATA_METHOD0, CLASS_String, MN_trim, FLAG_Method_Const, _DATA(String_trim), /*P=*/40,
	DATA_METHOD0, CLASS_Regex, MN_opHAS, FLAG_Method_Const, _DATA(Regex_opHAS), /*P=*/46,
	DATA_METHOD0, CLASS_System, MN_getIn, FLAG_Method_Static, _DATA(System_getIn), /*P=*/81,
	DATA_METHOD0, CLASS_System, MN_getOut, FLAG_Method_Static, _DATA(System_getOut), /*P=*/82,
	DATA_METHOD0, CLASS_System, MN_getErr, FLAG_Method_Static, _DATA(System_getErr), /*P=*/82,
	DATA_METHOD0, CLASS_System, MN_getProperty, FLAG_Method_Static, _DATA(System_getProperty), /*P=*/83,
	DATA_METHOD0, CLASS_System, MN_setProperty, FLAG_Method_Static, _DATA(System_setProperty), /*P=*/84,
	DATA_METHOD0, CLASS_System, MN_listProperties, FLAG_Method_Hidden, _DATA(System_listProperties), /*P=*/85,
	DATA_METHOD0, CLASS_System, MN_gc, FLAG_Method_Static, _DATA(System_gc), /*P=*/0,
	DATA_METHOD0, CLASS_System, MN_getTime, 0, _DATA(System_getTime), /*P=*/10,
	DATA_METHOD0, CLASS_Context, MN_setIn, FLAG_Method_Static, _DATA(Context_setIn), /*P=*/86,
	DATA_METHOD0, CLASS_Context, MN_setOut, FLAG_Method_Static, _DATA(Context_setOut), /*P=*/87,
	DATA_METHOD0, CLASS_Context, MN_setErr, FLAG_Method_Static, _DATA(Context_setErr), /*P=*/87,
	DATA_METHOD0, CLASS_Exception, MN_opOF, 0, _DATA(Exception_opOF), /*P=*/88,
	DATA_METHOD0, CLASS_NameSpace, MN_setConst, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(NameSpace_setConst), /*P=*/89,
	DATA_METHOD0, CLASS_Class, MN_setConst, FLAG_Method_Const|FLAG_Method_Hidden, _DATA(Class_setConst), /*P=*/89,
	DATA_METHOD0, CLASS_String, MN_isASCII, 0, _DATA(String_isASCII), /*P=*/11,
	DATA_METHOD0, CLASS_OutputStream, MN_isAutoFlush, 0, _DATA(OutputStream_isAutoFlush), /*P=*/11,
	DATA_METHOD0, CLASS_OutputStream, MN_setAutoFlush, 0, _DATA(OutputStream_setAutoFlush), /*P=*/90,
	DATA_METHOD0, CLASS_Context, MN_isDebug, 0, _DATA(Context_isDebug), /*P=*/11,
	DATA_METHOD0, CLASS_Context, MN_setDebug, 0, _DATA(Context_setDebug), /*P=*/90,
	DATA_METHOD0, CLASS_Context, MN_isVerbose, 0, _DATA(Context_isVerbose), /*P=*/11,
	DATA_METHOD0, CLASS_Context, MN_setVerbose, 0, _DATA(Context_setVerbose), /*P=*/90,
	DATA_TCAST, CLASS_String, CLASS_Iterator, FLAG_Translator_Total, _DATA(String_Iterator),
	DATA_TCAST, CLASS_String, CLASS_StringITR, FLAG_Translator_Total, _DATA(String_Iterator),
	DATA_TCAST, CLASS_Array, CLASS_Iterator, FLAG_Translator_Total, _DATA(Array_Iterator),
	DATA_TCAST, CLASS_Map, CLASS_Iterator, FLAG_Translator_Total, _DATA(DictMap_String__),
	DATA_TCAST, CLASS_Map, CLASS_StringITR, FLAG_Translator_Total, _DATA(DictMap_String__),
	DATA_TCAST, CLASS_Float, CLASS_Int, FLAG_Translator_Const|FLAG_Translator_Total|FLAG_Translator_Final, _DATA(Float_Int),
	DATA_TCAST, CLASS_String, CLASS_Int, FLAG_Translator_Const|FLAG_Translator_Total|FLAG_Translator_Final, _DATA(String_Int),
	DATA_TCAST, CLASS_Int, CLASS_Float, FLAG_Translator_Const|FLAG_Translator_Total|FLAG_Translator_Final, _DATA(Int_Float),
	DATA_TCAST, CLASS_Object, CLASS_Iterator, FLAG_Translator_Const|FLAG_Translator_Total, _DATA(Object_Iterator),
	DATA_TCAST, CLASS_Iterator, CLASS_Array, FLAG_Translator_Total, _DATA(Iterator_Array),
	DATA_TCAST, CLASS_Bytes, CLASS_InputStream, FLAG_Translator_Total, _DATA(Bytes_InputStream),
	DATA_TCAST, CLASS_String, CLASS_Regex, FLAG_Translator_Const|FLAG_Translator_Total, _DATA(String_Regex),
	DATA_TCAST, CLASS_InputStream, CLASS_StringITR, FLAG_Translator_Total|FLAG_Translator_Final, _DATA(knh_InputStream_String__),
	0
};
